language: r
cache: packages

r:
  - release
  - devel

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libssl-dev
      - libcurl4-openssl-dev
      - netcdf-bin
      - libnetcdf-dev
      - gdal-bin
      - libgdal-dev
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
